#ifndef RTBOT_JSONSCHEMA_H_
#define RTBOT_JSONSCHEMA_H_

#include <nlohmann/json.hpp>

using nlohmann::json;

static json rtbot_schema = ""
"{"
"  \"$id\": \"root\","
"  \"$schema\": \"http://json-schema.org/draft-07/schema#\","
"  \"type\": \"object\","
"  \"properties\": {"
"    \"title\": {"
"      \"type\": \"string\","
"      \"examples\": ["
"\"Peak detector\""
"      ]"
"    },"
"    \"description\": {"
"      \"type\": \"string\","
"      \"examples\": ["
"\"This is a program to detect peaks in ECG...\""
"      ]"
"    },"
"    \"date\": {"
"      \"type\": \"string\","
"      \"format\": \"date\""
"    },"
"    \"apiVersion\": {"
"      \"enum\": ["
"\"v1\""
"      ],"
"      \"default\": \"v1\""
"    },"
"    \"author\": {"
"      \"type\": \"string\","
"      \"examples\": ["
"\"Someone <someone@gmail.com>\""
"      ]"
"    },"
"    \"license\": {"
"      \"type\": \"string\","
"      \"examples\": ["
"\"MIT\","
"\"private\""
"      ]"
"    },"
"    \"entryOperator\": {"
"      \"type\": \"string\","
"      \"examples\": ["
"\"in1\","
"\"join1\""
"      ]"
"    },"
"    \"output\": {"
"      \"type\": \"object\","
"      \"patternProperties\": {"
"\"^[A-Z0-9a-t_-]+$\": {"
"\"type\": \"array\","
"\"items\": {"
"\"type\": \"string\","
"\"examples\": ["
"\"o1\","
"\"o2\""
"]"
"}"
"}"
"      },"
"      \"examples\": ["
"\"join1\","
"\"join2\""
"      ]"
"    },"
"    \"operators\": {"
"      \"type\": \"array\","
"      \"items\": {"
"\"oneOf\": ["
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"value\": {"
"\"type\": \"number\","
"\"description\": \"The constant to add to the incoming messages.\""
"},"
"\"type\": {"
"\"enum\": ["
"\"Add\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\","
"\"value\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"type\": {"
"\"enum\": ["
"\"And\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"coeff\": {"
"\"type\": \"array\","
"\"description\": \"The list of auto-regression coefficients.\","
"\"examples\": ["
"["
"1,"
"2"
"]"
"],"
"\"minItems\": 1,"
"\"items\": {"
"\"type\": \"number\""
"}"
"},"
"\"type\": {"
"\"enum\": ["
"\"AutoRegressive\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\","
"\"coeff\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"value\": {"
"\"type\": \"number\","
"\"examples\": ["
"3.14,"
"2.718"
"],"
"\"description\": \"The constant to emit when required.\""
"},"
"\"type\": {"
"\"enum\": ["
"\"Constant\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\","
"\"value\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"type\": {"
"\"enum\": ["
"\"Count\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"type\": {"
"\"enum\": ["
"\"CumulativeSum\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"type\": {"
"\"enum\": ["
"\"Difference\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"type\": {"
"\"enum\": ["
"\"Division\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"value\": {"
"\"type\": \"integer\","
"\"description\": \"The reference value\""
"},"
"\"type\": {"
"\"enum\": ["
"\"EqualTo\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\","
"\"value\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"coeff\": {"
"\"type\": \"array\","
"\"examples\": ["
"["
"1,"
"0,"
"-1"
"]"
"],"
"\"description\": \"The vector of coefficients to be combined with the buffered message values.\","
"\"items\": {"
"\"type\": \"number\""
"}"
"},"
"\"type\": {"
"\"enum\": ["
"\"FiniteImpulseResponse\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\","
"\"coeff\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"value\": {"
"\"type\": \"integer\","
"\"description\": \"The reference value\""
"},"
"\"type\": {"
"\"enum\": ["
"\"GreaterThan\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\","
"\"value\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"type\": {"
"\"enum\": ["
"\"Identity\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"value\": {"
"\"type\": \"integer\","
"\"description\": \"The reference value\""
"},"
"\"type\": {"
"\"enum\": ["
"\"LessThan\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\","
"\"value\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"coeff\": {"
"\"type\": \"array\","
"\"description\": \"The list of coefficients.\","
"\"minItems\": 2,"
"\"items\": {"
"\"type\": \"number\""
"}"
"},"
"\"type\": {"
"\"enum\": ["
"\"Linear\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"type\": {"
"\"enum\": ["
"\"Minus\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"n\": {"
"\"type\": \"integer\","
"\"description\": \"The window size, in grid steps, to be used in the computation.\""
"},"
"\"type\": {"
"\"enum\": ["
"\"MovingAverage\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\","
"\"n\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"type\": {"
"\"enum\": ["
"\"Multiplication\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"type\": {"
"\"enum\": ["
"\"Or\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"n\": {"
"\"type\": \"integer\","
"\"description\": \"The window size, in grid steps, to be used in the computation.\""
"},"
"\"type\": {"
"\"enum\": ["
"\"PeakDetector\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\","
"\"n\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"type\": {"
"\"enum\": ["
"\"Plus\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"value\": {"
"\"type\": \"number\","
"\"description\": \"The exponent.\""
"},"
"\"type\": {"
"\"enum\": ["
"\"Power\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\","
"\"value\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"value\": {"
"\"type\": \"number\","
"\"description\": \"The factor to use to scale the messages.\""
"},"
"\"type\": {"
"\"enum\": ["
"\"Scale\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\","
"\"value\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"n\": {"
"\"type\": \"number\","
"\"description\": \"The number of grid steps to use to compute the standard deviation.\""
"},"
"\"type\": {"
"\"enum\": ["
"\"StandardDeviation\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\","
"\"n\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"dt\": {"
"\"type\": \"integer\","
"\"default\": 1,"
"\"minimum\": 1,"
"\"description\": \"The constant that defines the time grid.\""
"},"
"\"times\": {"
"\"type\": \"integer\","
"\"default\": 1,"
"\"description\": \"The multiplier to apppy.\""
"},"
"\"type\": {"
"\"enum\": ["
"\"TimeShift\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"value\": {"
"\"type\": \"number\","
"\"description\": \"The default value of the variable\","
"\"default\": 0"
"},"
"\"type\": {"
"\"enum\": ["
"\"Variable\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator.\","
"\"examples\": ["
"\"demul1\""
"]"
"},"
"\"numOutputPorts\": {"
"\"type\": \"integer\","
"\"description\": \"The number of output ports through which data will be routed.\","
"\"default\": 1,"
"\"minimum\": 1,"
"\"examples\": ["
"2"
"]"
"},"
"\"type\": {"
"\"enum\": ["
"\"Demultiplexer\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"numPorts\": {"
"\"type\": \"integer\","
"\"description\": \"The number of possible input ports. Useful if more than one input is taken.\","
"\"default\": 1,"
"\"minimum\": 1"
"},"
"\"type\": {"
"\"enum\": ["
"\"Input\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"numPorts\": {"
"\"type\": \"integer\","
"\"description\": \"The number of input ports.\","
"\"default\": 2,"
"\"minimum\": 2"
"},"
"\"type\": {"
"\"enum\": ["
"\"Join\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"},"
"{"
"\"type\": \"object\","
"\"properties\": {"
"\"id\": {"
"\"type\": \"string\","
"\"description\": \"The id of the operator\""
"},"
"\"numPorts\": {"
"\"type\": \"integer\","
"\"description\": \"The number of ports.\","
"\"default\": 1,"
"\"minimum\": 1"
"},"
"\"type\": {"
"\"enum\": ["
"\"Output\""
"]"
"}"
"},"
"\"required\": ["
"\"type\","
"\"id\""
"]"
"}"
"]"
"      }"
"    },"
"    \"connections\": {"
"      \"type\": \"array\","
"      \"items\": {"
"\"type\": \"object\","
"\"properties\": {"
"\"from\": {"
"\"type\": \"string\","
"\"examples\": ["
"\"ma1\""
"]"
"},"
"\"to\": {"
"\"type\": \"string\","
"\"examples\": ["
"\"std\""
"]"
"},"
"\"fromPort\": {"
"\"type\": \"string\","
"\"examples\": ["
"\"o1\""
"]"
"},"
"\"toPort\": {"
"\"type\": \"string\","
"\"examples\": ["
"\"i1\""
"]"
"}"
"},"
"\"required\": ["
"\"from\","
"\"to\""
"],"
"\"additionalProperties\": false"
"      }"
"    }"
"  },"
"  \"required\": ["
"    \"operators\","
"    \"connections\","
"    \"entryOperator\""
"  ],"
"  \"additionalProperties\": true"
"}"
""_json;
#endif