name: Preview Changes

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - edited
      - synchronize
      - review_requested
      - ready_for_review

env:
  NODE_OPTIONS: "--max_old_space_size=16384"

jobs:
  tests:
    if: github.event.pull_request.draft == false
    name: Test core
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          
      # Force Install pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
          
      - run: pnpm install --no-frozen-lockfile

      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Mount Bazel cache
      - name: Mount bazel caches
        uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: bazel-cache-${{ hashFiles('**/BUILD.bazel', '**/*.bzl', 'WORKSPACE', '**/*.cpp', '**/*.h', '**/*.rs') || 'default' }}
          restore-keys: |
            bazel-cache-

      # Setup Bazelisk
      - uses: bazelbuild/setup-bazelisk@v2
        with:
          skip-cache: true

      # Run Bazel tests
      - name: Test core
        run: bazelisk test //libs/core/test

      - name: Test std
        run: bazelisk test //libs/std/test

      - name: Test api
        run: bazelisk test //libs/api/test

      - name: Test python
        run: |
          bazel test --incompatible_use_python_toolchains=false --python_path=$(which python) //libs/wrappers/python:rtbot_test

      - name: Test javascript
        run: bazelisk test //libs/wrappers/javascript:test
