name: Preview Changes

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - edited
      - synchronize
      - review_requested
      - ready_for_review

env:
  NODE_OPTIONS: "--max_old_space_size=16384"

jobs:
  tests:
    if: github.event.pull_request.draft == false
    name: Test core
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      # 3️⃣ Install pnpm globally
      - run: npm install -g pnpm@8

      # 4️⃣ Install JS dependencies
      - run: pnpm install --no-frozen-lockfile

      # 5️⃣ Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 6️⃣ Mount Bazel cache
      - name: Mount bazel caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: bazel-cache-${{ hashFiles('**/BUILD.bazel', '**/*.bzl', 'WORKSPACE', '**/*.cpp', '**/*.h', '**/*.rs') }}
          restore-keys: bazel-cache-

      # 7️⃣ Setup Bazelisk
      - uses: bazelbuild/setup-bazelisk@v2

      # 8️⃣ Run Bazel tests
      - name: Test lib
        run: bazelisk test //libs/core/test

      - name: Test std
        run: bazelisk test //libs/std/test

      - name: Test api
        run: bazelisk test //libs/api/test

      - name: Test python
        run: |
          bazel test --incompatible_use_python_toolchains=false --python_path=$(which python) //libs/wrappers/python:rtbot_test

      - name: Test javascript
        run: bazelisk test //libs/wrappers/javascript:test
