name: Preview Changes
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - edited
      - synchronize
      - review_requested
      - ready_for_review

env:
  NODE_OPTIONS: "--max_old_space_size=16384"

jobs:
  tests:
    if: github.event.pull_request.draft == false
    name: Test core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
          run_install: |
            - args: [--no-frozen-lockfile]
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Mount bazel caches
        uses: actions/cache@v3
        with:
          path: |
            "~/.cache/bazel"
          key: bazel-cache-${{ hashFiles('**/BUILD.bazel', '**/*.bzl', 'WORKSPACE', '**/*.cpp', '**/*.h', '**/*.rs') }}
          restore-keys: bazel-cache-
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Test lib
        run: |
          bazelisk test //libs/core/lib/test
      - name: Test std
        run: |
          bazelisk test //libs/core/std/test
      - name: Test api
        run: |
          bazelisk test //libs/core/api/test
      - name: Test finance
        run: |
          bazelisk test //libs/core/finance/test
      - name: Test python
        run: |
          # TODO: make sure we don't have to build the wheel and install it
          # in order to make the test to pass
          bazelisk build //libs/core/wrappers/python:rtbot_wheel
          pip install --force-reinstall dist/bin/libs/core/wrappers/python/rtbot-_VERSION_-py3-none-manylinux2014_x86_64.whl
          bazelisk test //libs/core/wrappers/python:rtbot_test
      - name: Test javascript
        run: |
          bazelisk test //libs/core/wrappers/javascript:test
