name: Preview Changes
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - edited
      - synchronize
      - review_requested
      - ready_for_review

env:
  NODE_OPTIONS: "--max_old_space_size=16384"

jobs:
  tests:
    if: github.event.pull_request.draft == false
    name: Test core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
          run_install: |
            - args: [--no-frozen-lockfile]
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Test lib
        run: |
          bazelisk test //libs/core/lib/test:test
      - name: Test std
        run: |
          bazelisk test //libs/core/std/test:test
      - name: Test api
        run: |
          bazelisk test //libs/core/std/api:test
      - name: Test finance
        run: |
          bazelisk test //libs/core/std/finance:test  
