# Cut a release whenever a new tag is pushed to the repo.
# You should use an annotated tag, like `git tag -a v1.2.3`
# and put the release notes into the commit message for the tag.
name: Release

permissions:
  contents: read

on:
  push:
    tags:
      - "v*.*.*"
  release:
    types: [published]

jobs:
  tests:
    name: Test (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: |
            - args: [--no-frozen-lockfile]
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm
      - name: Setup Bazel toolchain
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Run test suite
        run: bazel test //...

  build_npm:
    name: Build npm package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: |
            - args: [--no-frozen-lockfile]
      - name: Setup Bazel toolchain
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Build npm package
        run: bazel build --stamp //libs/wrappers/javascript:js
      - uses: actions/upload-artifact@v5
        with:
          name: npm-rtbot.tar
          path: dist/bin/libs/wrappers/javascript/js
      - name: Generate jsonschema
        run: bazel build //libs/api:jsonschema
      - uses: actions/upload-artifact@v5
        with:
          name: jsonschema.tar
          path: dist/bin/libs/api/jsonschema

  publish:
    needs:
      - tests
      - build_npm
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - name: Prepare release
        run: .github/workflows/release_prep.sh ${{ env.GITHUB_REF_NAME }} > release_notes.txt
      - uses: actions/download-artifact@v5
        with:
          name: npm-rtbot.tar
          path: npm-rtbot
      - uses: actions/download-artifact@v5
        with:
          name: jsonschema.tar
          path: jsonschema
      - name: Organize release assets
        run: |
          # copy repo readme to main npm package
          cp README.md ./npm-rtbot
          # package npm files, which will be used on the github release
          tar -zcvf rtbot-npm-${{ github.ref_name }}.tar.gz npm-rtbot
      - name: Release Npm Packages
        run: |
          rm -rf node_modules package.json pnpm pnpm-lock.yaml
          cd npm-rtbot && pnpm publish --no-git-checks --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release GitHub
        uses: softprops/action-gh-release@v1
        with:
          # Use GH feature to populate the changelog automatically
          generate_release_notes: true
          body_path: release_notes.txt
          files: |
            *.tar.gz
            jsonschema/*
          fail_on_unmatched_files: true
